version: '3'

services:
  mc-proxy:
    image: haveachin/infrared:1.3.4
    container_name: mc-proxy
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    volumes:
      - "./proxy-configs:/configs"
    expose:
      - "25565"
    environment:
      INFRARED_CONFIG_PATH: "/configs"
  mc-wills-creative:
    image: ghcr.io/itzg/minecraft-server:latest
    container_name: mc-wills-creative
    restart: unless-stopped
    environment: 
      EULA: "TRUE"
      TYPE: PAPER
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      # PAPERMC_FLAGS: "--nojline"
      # TZ: "Australia/Canberra"
      # MEMORYSIZE: "4G"
    volumes:
      - ./wills-creative-data/:/data:rw
    ports: 
      - "6969:25565"
      - "23493:25575"
  mc-wills-survival:
    image: ghcr.io/itzg/minecraft-server:latest
    container_name: mc-wills-survival
    restart: unless-stopped
    environment: 
      EULA: "TRUE"
      TYPE: PAPER
      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
      # PAPERMC_FLAGS: "--nojline"
      # TZ: "Australia/Canberra"
      MEMORYSIZE: "8G"
    volumes:
      - ./wills-survival-data/:/data:rw
    ports: 
      - "42069:25565"
      - "23491:25575"
