services:
  proxy:
    image: haveachin/infrared:1.3.4
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    volumes:
      - "./proxy-configs:/configs"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      INFRARED_CONFIG_PATH: "/configs"
  creative:
    image: ghcr.io/itzg/minecraft-server:latest
    restart: unless-stopped
    environment: 
      EULA: "TRUE"
      TYPE: PAPER
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      # PAPERMC_FLAGS: "--nojline"
      # TZ: "Australia/Canberra"
      # MEMORYSIZE: "4G"
    volumes:
      - ./creative-data/:/data:rw
    ports: 
      - "25563:25565"
  survival:
    image: ghcr.io/itzg/minecraft-server:latest
    restart: unless-stopped
    ports:
      - "25562:25565"
    environment: 
      EULA: "TRUE"
      TYPE: PAPER
      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
      # PAPERMC_FLAGS: "--nojline"
      # TZ: "Australia/Canberra"
      MEMORYSIZE: "8G"
    volumes:
      - ./survival-data/:/data:rw
